// Mirrors the categories seeded in supabase/migrations/20260930000200_reference_data.sql
// (a unit test keeps them in sync). Used by public pages that don't query the database.
export const CATEGORIES: { code: string; archive: string; name: string }[] = [
  { code: "cs.AI", archive: "cs", name: "Artificial Intelligence" },
  { code: "cs.AR", archive: "cs", name: "Hardware Architecture" },
  { code: "cs.CC", archive: "cs", name: "Computational Complexity" },
  { code: "cs.CE", archive: "cs", name: "Computational Engineering, Finance, and Science" },
  { code: "cs.CG", archive: "cs", name: "Computational Geometry" },
  { code: "cs.CL", archive: "cs", name: "Computation and Language" },
  { code: "cs.CR", archive: "cs", name: "Cryptography and Security" },
  { code: "cs.CV", archive: "cs", name: "Computer Vision and Pattern Recognition" },
  { code: "cs.CY", archive: "cs", name: "Computers and Society" },
  { code: "cs.DB", archive: "cs", name: "Databases" },
  { code: "cs.DC", archive: "cs", name: "Distributed, Parallel, and Cluster Computing" },
  { code: "cs.DL", archive: "cs", name: "Digital Libraries" },
  { code: "cs.DM", archive: "cs", name: "Discrete Mathematics" },
  { code: "cs.DS", archive: "cs", name: "Data Structures and Algorithms" },
  { code: "cs.ET", archive: "cs", name: "Emerging Technologies" },
  { code: "cs.FL", archive: "cs", name: "Formal Languages and Automata Theory" },
  { code: "cs.GL", archive: "cs", name: "General Literature" },
  { code: "cs.GR", archive: "cs", name: "Graphics" },
  { code: "cs.GT", archive: "cs", name: "Computer Science and Game Theory" },
  { code: "cs.HC", archive: "cs", name: "Human-Computer Interaction" },
  { code: "cs.IR", archive: "cs", name: "Information Retrieval" },
  { code: "cs.IT", archive: "cs", name: "Information Theory" },
  { code: "cs.LG", archive: "cs", name: "Machine Learning" },
  { code: "cs.LO", archive: "cs", name: "Logic in Computer Science" },
  { code: "cs.MA", archive: "cs", name: "Multiagent Systems" },
  { code: "cs.MM", archive: "cs", name: "Multimedia" },
  { code: "cs.MS", archive: "cs", name: "Mathematical Software" },
  { code: "cs.NA", archive: "cs", name: "Numerical Analysis" },
  { code: "cs.NE", archive: "cs", name: "Neural and Evolutionary Computing" },
  { code: "cs.NI", archive: "cs", name: "Networking and Internet Architecture" },
  { code: "cs.OH", archive: "cs", name: "Other Computer Science" },
  { code: "cs.OS", archive: "cs", name: "Operating Systems" },
  { code: "cs.PF", archive: "cs", name: "Performance" },
  { code: "cs.PL", archive: "cs", name: "Programming Languages" },
  { code: "cs.RO", archive: "cs", name: "Robotics" },
  { code: "cs.SC", archive: "cs", name: "Symbolic Computation" },
  { code: "cs.SD", archive: "cs", name: "Sound" },
  { code: "cs.SE", archive: "cs", name: "Software Engineering" },
  { code: "cs.SI", archive: "cs", name: "Social and Information Networks" },
  { code: "cs.SY", archive: "cs", name: "Systems and Control" },
  { code: "stat.ML", archive: "stat", name: "Machine Learning (Statistics)" },
  { code: "stat.ME", archive: "stat", name: "Methodology" },
  { code: "stat.AP", archive: "stat", name: "Applications" },
  { code: "math.OC", archive: "math", name: "Optimization and Control" },
  { code: "math.PR", archive: "math", name: "Probability" },
  { code: "math.ST", archive: "math", name: "Statistics Theory" },
  { code: "eess.AS", archive: "eess", name: "Audio and Speech Processing" },
  { code: "eess.IV", archive: "eess", name: "Image and Video Processing" },
  { code: "eess.SP", archive: "eess", name: "Signal Processing" },
  { code: "eess.SY", archive: "eess", name: "Systems and Control" },
  { code: "q-bio.QM", archive: "q-bio", name: "Quantitative Methods" },
  { code: "q-bio.NC", archive: "q-bio", name: "Neurons and Cognition" },
  { code: "econ.EM", archive: "econ", name: "Econometrics" },
  { code: "econ.GN", archive: "econ", name: "General Economics" },
  { code: "physics.soc-ph", archive: "physics", name: "Physics and Society" },
  { code: "physics.comp-ph", archive: "physics", name: "Computational Physics" },
  { code: "quant-ph", archive: "quant-ph", name: "Quantum Physics" },
];
